### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by jonathanslenders** [PSoWin/yawinpty#1]
Just a thank you for this package! It works really great.
Can I ask you what the original reason for creating this wrapper is?

**Comment by TitanSnow** [comment]
Pseudo terminal is used to net login, capture output of long-time-running program, graphic terminal emulator etc. On POSIX, it’s easy to use pty-related syscalls to open a pty, but on Windows the commonly used way is to use the library winpty. Half year ago, I’m writing a graphic program to show  output of one console program in python. I did it easily with pty module in python’s standard library on Linux, but the pty module is not on Windows. That time there was no winpty wrapper for python, so I came up with the idea of writing one.

**Comment by jonathanslenders** [comment]
Cool! Thanks :-)
